FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

# Install poetry
RUN pip install poetry

# Copy poetry.lock and pyproject.toml
COPY poetry.lock pyproject.toml ./
COPY src ./src

RUN poetry build

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --only main
RUN pip install dist/*.whl

RUN rm -rf dist/ src/ poetry.lock pyproject.toml

ENTRYPOINT ["python"]
