FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

# Install poetry
RUN pip install poetry

# Copy poetry.lock and pyproject.toml
COPY poetry.lock pyproject.toml ./
COPY src /opt/ml/processing/input/code/src

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --only main

ENTRYPOINT ["python"]
