FROM apache/airflow:2.6.3-python3.10

# Install poetry
RUN pip install poetry

# Copy poetry.lock and pyproject.toml
COPY poetry.lock pyproject.toml ./

# Install src
COPY src/ ./src/
RUN poetry build

# Install dependencies
RUN poetry export --without-hashes --format=requirements.txt > requirements.txt
RUN pip install -r requirements.txt ./dist/*.whl

USER root
RUN rm -rf src/ poetry.lock pyproject.toml requirements.txt dist/
USER airflow
