FROM 763104351884.dkr.ecr.eu-west-1.amazonaws.com/pytorch-training:2.1.0-cpu-py310-ubuntu20.04-sagemaker

# Install poetry
RUN pip install poetry

# Copy poetry.lock and pyproject.toml
COPY poetry.lock pyproject.toml ./
COPY src ./src

# Install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --only main
