FROM apache/airflow:2.6.3-python3.10

# Install poetry
RUN pip install poetry

# Copy poetry.lock and pyproject.toml
COPY poetry.lock pyproject.toml ./

# Install src
COPY src/ ./src/
RUN poetry config virtualenvs.create false && \
    poetry install --only-root

USER root
RUN rm -rf src/
USER airflow

# Install dependencies
RUN poetry export --without-hashes --format=requirements.txt > requirements.txt
RUN pip install -r requirements.txt
