FROM apache/airflow:2.6.3-python3.10

# Install poetry
RUN pip install poetry

# Copy poetry.lock and pyproject.toml
COPY poetry.lock pyproject.toml ./

# Install src
COPY src/ ./src/
RUN poetry build
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

# Install dependencies
RUN pip install -r requirements.txt ./dist/*.whl

USER root
RUN rm -rf src/ poetry.lock pyproject.toml dist/ requirements.txt
USER airflow
