---
name: Image build

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows.build.yaml'
      - '**/Containerfile*'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  build:
    name: Build
    env:
      IMAGE_PREFIX: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/benchoncy-devops-masters-project/
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - name: metaflow
            file: Containerfile.metaflow
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ECR registry
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_PREFIX }}${{ matrix.name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=pr
            type=ref,event=branch
          flavor: |
            latest=false

      - name: Build & Push
        id: build
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ matrix.file }}
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
